// <auto-generated />
using System;
using CognitiveMemory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CognitiveMemory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MemoryDbContext))]
    [Migration("20260222193225_AddCompanionCognitiveControlSystem")]
    partial class AddCompanionCognitiveControlSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.ClaimContradictionEntity", b =>
                {
                    b.Property<Guid>("ContradictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimBId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ContradictionId");

                    b.HasIndex("CompanionId", "ClaimAId", "ClaimBId")
                        .IsUnique();

                    b.ToTable("ClaimContradictions", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.ClaimEvidenceEntity", b =>
                {
                    b.Property<Guid>("EvidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExcerptOrSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("Strength")
                        .HasColumnType("double precision");

                    b.HasKey("EvidenceId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("CompanionId", "ClaimId", "CapturedAtUtc");

                    b.ToTable("ClaimEvidence", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.CompanionCognitiveProfileAuditEntity", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiffJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FromProfileVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid?>("ToProfileVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("AuditId");

                    b.HasIndex("CompanionId", "CreatedAtUtc");

                    b.HasIndex("CompanionId", "Action", "CreatedAtUtc");

                    b.ToTable("CompanionCognitiveProfileAudits", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.CompanionCognitiveProfileEntity", b =>
                {
                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActiveProfileVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StagedProfileVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("CompanionId");

                    b.HasIndex("ActiveProfileVersionId");

                    b.HasIndex("StagedProfileVersionId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("CompanionCognitiveProfiles", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.CompanionCognitiveProfileVersionEntity", b =>
                {
                    b.Property<Guid>("ProfileVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("text");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("text");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompiledRuntimeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProfileHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProfileJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("ProfileVersionId");

                    b.HasIndex("CompanionId", "CreatedAtUtc");

                    b.HasIndex("CompanionId", "ProfileHash")
                        .IsUnique();

                    b.HasIndex("CompanionId", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("CompanionId", "ValidationStatus", "CreatedAtUtc");

                    b.ToTable("CompanionCognitiveProfileVersions", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.CompanionCognitiveRuntimeTraceEntity", b =>
                {
                    b.Property<Guid>("TraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ProfileVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestCorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("TraceId");

                    b.HasIndex("CompanionId", "CreatedAtUtc");

                    b.HasIndex("CompanionId", "ProfileVersionId", "CreatedAtUtc");

                    b.HasIndex("CompanionId", "RequestCorrelationId", "CreatedAtUtc");

                    b.HasIndex("CompanionId", "SessionId", "CreatedAtUtc");

                    b.ToTable("CompanionCognitiveRuntimeTraces", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.CompanionEntity", b =>
                {
                    b.Property<Guid>("CompanionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveCognitiveProfileVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("BirthDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitialMemoryText")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelHint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OriginStory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("CompanionId");

                    b.HasIndex("ActiveCognitiveProfileVersionId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("UserId", "Name");

                    b.HasIndex("UserId", "UpdatedAtUtc");

                    b.ToTable("Companions", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.ConflictEscalationAlertEntity", b =>
                {
                    b.Property<Guid>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ContradictionCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Predicate")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ValuesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AlertId");

                    b.HasIndex("CompanionId", "Subject", "Predicate", "Status");

                    b.ToTable("ConflictEscalationAlerts", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.ConsolidationPromotionEntity", b =>
                {
                    b.Property<Guid>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EpisodicEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SemanticClaimId")
                        .HasColumnType("uuid");

                    b.HasKey("PromotionId");

                    b.HasIndex("EpisodicEventId")
                        .IsUnique();

                    b.HasIndex("ProcessedAtUtc");

                    b.ToTable("ConsolidationPromotions", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.EpisodicMemoryEventEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("What")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Who")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("EventId");

                    b.HasIndex("CompanionId", "SessionId", "OccurredAt");

                    b.ToTable("EpisodicMemoryEvents", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.EventConsumerCheckpointEntity", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConsumerName", "EventId");

                    b.HasIndex("ProcessedAtUtc");

                    b.ToTable("EventConsumerCheckpoints", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.MemoryRelationshipEntity", b =>
                {
                    b.Property<Guid>("RelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FromType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("Strength")
                        .HasColumnType("double precision");

                    b.Property<string>("ToId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ToType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RelationshipId");

                    b.HasIndex("CompanionId", "SessionId", "RelationshipType", "Status");

                    b.HasIndex("CompanionId", "SessionId", "FromType", "FromId", "Status");

                    b.HasIndex("CompanionId", "SessionId", "ToType", "ToId", "Status");

                    b.HasIndex("CompanionId", "SessionId", "FromType", "FromId", "ToType", "ToId", "RelationshipType")
                        .IsUnique();

                    b.ToTable("MemoryRelationships", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastAttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("EventId");

                    b.HasIndex("AggregateId");

                    b.HasIndex("Status", "OccurredAtUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.PortalUserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("PortalUsers", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.ProceduralRoutineEntity", b =>
                {
                    b.Property<Guid>("RoutineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheckpointsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoutineId");

                    b.HasIndex("CompanionId", "Trigger");

                    b.ToTable("ProceduralRoutines", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.ProceduralRoutineMetricEntity", b =>
                {
                    b.Property<Guid>("RoutineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastOutcomeSummary")
                        .HasColumnType("text");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoutineId");

                    b.HasIndex("CompanionId", "Trigger");

                    b.HasIndex("CompanionId", "UpdatedAtUtc");

                    b.ToTable("ProceduralRoutineMetrics", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.ScheduledActionEntity", b =>
                {
                    b.Property<Guid>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RunAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ActionId");

                    b.HasIndex("CompanionId", "SessionId", "CreatedAtUtc");

                    b.HasIndex("CompanionId", "Status", "RunAtUtc");

                    b.ToTable("ScheduledActions", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.SelfPreferenceEntity", b =>
                {
                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CompanionId", "Key");

                    b.HasIndex("CompanionId");

                    b.ToTable("SelfPreferences", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.SemanticClaimEmbeddingEntity", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Dimensions")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EmbeddedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("VectorJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClaimId");

                    b.HasIndex("EmbeddedAtUtc");

                    b.ToTable("SemanticClaimEmbeddings", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.SemanticClaimEntity", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Predicate")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("SupersededByClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClaimId");

                    b.HasIndex("SupersededByClaimId");

                    b.HasIndex("CompanionId", "Subject", "Predicate", "Status");

                    b.ToTable("SemanticClaims", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.SubconsciousDebateMetricEntity", b =>
                {
                    b.Property<Guid>("DebateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClaimsApplied")
                        .HasColumnType("integer");

                    b.Property<int>("ClaimsProposed")
                        .HasColumnType("integer");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ContradictionsDetected")
                        .HasColumnType("integer");

                    b.Property<double>("ConvergenceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<double>("FinalConfidence")
                        .HasColumnType("double precision");

                    b.Property<bool>("RequiresUserInput")
                        .HasColumnType("boolean");

                    b.Property<int>("TurnCount")
                        .HasColumnType("integer");

                    b.HasKey("DebateId");

                    b.HasIndex("CompanionId", "CreatedAtUtc");

                    b.ToTable("SubconsciousDebateMetrics", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.SubconsciousDebateOutcomeEntity", b =>
                {
                    b.Property<Guid>("DebateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApplyError")
                        .HasColumnType("text");

                    b.Property<string>("ApplyStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutcomeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OutcomeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("DebateId");

                    b.HasIndex("CompanionId", "OutcomeHash");

                    b.ToTable("SubconsciousDebateOutcomes", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.SubconsciousDebateSessionEntity", b =>
                {
                    b.Property<Guid>("DebateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TopicKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("TriggerEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriggerEventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TriggerPayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DebateId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("TriggerEventId");

                    b.HasIndex("CompanionId", "SessionId", "TopicKey", "State");

                    b.HasIndex("CompanionId", "SessionId", "TopicKey", "TriggerEventId")
                        .IsUnique();

                    b.ToTable("SubconsciousDebateSessions", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.SubconsciousDebateTurnEntity", b =>
                {
                    b.Property<Guid>("TurnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DebateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StructuredPayloadJson")
                        .HasColumnType("text");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer");

                    b.HasKey("TurnId");

                    b.HasIndex("CompanionId", "CreatedAtUtc");

                    b.HasIndex("CompanionId", "DebateId", "TurnNumber")
                        .IsUnique();

                    b.ToTable("SubconsciousDebateTurns", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.ToolInvocationAuditEntity", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsWrite")
                        .HasColumnType("boolean");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("AuditId");

                    b.HasIndex("CompanionId", "ToolName", "ExecutedAtUtc");

                    b.ToTable("ToolInvocationAudits", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.UserProfileProjectionEntity", b =>
                {
                    b.Property<Guid>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CompanionId", "Key");

                    b.HasIndex("CompanionId", "UpdatedAtUtc");

                    b.ToTable("UserProfileProjections", (string)null);
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.ClaimEvidenceEntity", b =>
                {
                    b.HasOne("CognitiveMemory.Infrastructure.Persistence.Entities.SemanticClaimEntity", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.CompanionCognitiveProfileAuditEntity", b =>
                {
                    b.HasOne("CognitiveMemory.Infrastructure.Persistence.Entities.CompanionEntity", null)
                        .WithMany()
                        .HasForeignKey("CompanionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.CompanionCognitiveProfileEntity", b =>
                {
                    b.HasOne("CognitiveMemory.Infrastructure.Persistence.Entities.CompanionEntity", null)
                        .WithMany()
                        .HasForeignKey("CompanionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.CompanionCognitiveProfileVersionEntity", b =>
                {
                    b.HasOne("CognitiveMemory.Infrastructure.Persistence.Entities.CompanionEntity", null)
                        .WithMany()
                        .HasForeignKey("CompanionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.CompanionCognitiveRuntimeTraceEntity", b =>
                {
                    b.HasOne("CognitiveMemory.Infrastructure.Persistence.Entities.CompanionEntity", null)
                        .WithMany()
                        .HasForeignKey("CompanionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CognitiveMemory.Infrastructure.Persistence.Entities.SemanticClaimEmbeddingEntity", b =>
                {
                    b.HasOne("CognitiveMemory.Infrastructure.Persistence.Entities.SemanticClaimEntity", null)
                        .WithOne()
                        .HasForeignKey("CognitiveMemory.Infrastructure.Persistence.Entities.SemanticClaimEmbeddingEntity", "ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
