// <auto-generated />
using System;
using CognitiveMemory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CognitiveMemory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MemoryDbContext))]
    partial class MemoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CognitiveMemory.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("LastReinforcedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LiteralValue")
                        .HasColumnType("text");

                    b.Property<Guid?>("ObjectEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Predicate")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubjectEntityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("ClaimId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("Claims", t =>
                        {
                            t.HasCheckConstraint("ck_claim_object_or_literal", "(\"ObjectEntityId\" IS NULL) <> (\"LiteralValue\" IS NULL)");
                        });
                });

            modelBuilder.Entity("CognitiveMemory.Domain.Entities.ClaimCalibration", b =>
                {
                    b.Property<Guid>("CalibrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReasonCodesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RecommendedConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("SourceEventRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("CalibrationId");

                    b.HasIndex("ClaimId", "CreatedAt");

                    b.ToTable("ClaimCalibrations");
                });

            modelBuilder.Entity("CognitiveMemory.Domain.Entities.ClaimInsight", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("KeywordsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceEventRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClaimId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("ClaimInsights");
                });

            modelBuilder.Entity("CognitiveMemory.Domain.Entities.Contradiction", b =>
                {
                    b.Property<Guid>("ContradictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimBId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("ContradictionId");

                    b.HasIndex("ClaimAId", "ClaimBId")
                        .IsUnique();

                    b.ToTable("Contradictions");
                });

            modelBuilder.Entity("CognitiveMemory.Domain.Entities.Evidence", b =>
                {
                    b.Property<Guid>("EvidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExcerptOrSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("Strength")
                        .HasColumnType("double precision");

                    b.HasKey("EvidenceId");

                    b.HasIndex("ClaimId");

                    b.ToTable("Evidence");
                });

            modelBuilder.Entity("CognitiveMemory.Domain.Entities.MemoryEntity", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EntityId");

                    b.HasIndex("Type", "Name")
                        .IsUnique();

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("CognitiveMemory.Domain.Entities.OutboxEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("EventId");

                    b.HasIndex("EventType", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status", "AvailableAt");

                    b.ToTable("OutboxEvents");
                });

            modelBuilder.Entity("CognitiveMemory.Domain.Entities.PolicyDecision", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReasonCodesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RiskScore")
                        .HasColumnType("double precision");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("DecisionId");

                    b.HasIndex("SourceType", "SourceRef", "CreatedAt");

                    b.ToTable("PolicyDecisions");
                });

            modelBuilder.Entity("CognitiveMemory.Domain.Entities.SourceDocument", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("DocumentId");

                    b.HasIndex("SourceType", "SourceRef", "ContentHash")
                        .IsUnique();

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("CognitiveMemory.Domain.Entities.ToolExecution", b =>
                {
                    b.Property<Guid>("ExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ExecutionId");

                    b.HasIndex("ToolName", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("ToolExecutions");
                });

            modelBuilder.Entity("CognitiveMemory.Domain.Entities.Evidence", b =>
                {
                    b.HasOne("CognitiveMemory.Domain.Entities.Claim", "Claim")
                        .WithMany("Evidence")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("CognitiveMemory.Domain.Entities.Claim", b =>
                {
                    b.Navigation("Evidence");
                });
#pragma warning restore 612, 618
        }
    }
}
